# Generated by Django 6.0 on 2025-12-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('category', models.CharField(choices=[('Food', 'Food 🍔'), ('Travel', 'Travel 🚌'), ('Shopping', 'Shopping 🛍️'), ('Bills', 'Bills 🧾'), ('Others', 'Others 🤷\u200d♂️')], max_length=20)),
                ('date', models.DateField()),
            ],
        ),
    ]
