# Generated by Django 6.0 on 2025-12-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food', 'Food '), ('Travel', 'Travel '), ('Entertainment', 'Entertainment '), ('EMI/Loans', 'EMI/Loans '), ('Shopping', 'Shopping '), ('Bills', 'Bills '), ('Others', 'Others ️')], max_length=20),
        ),
    ]
